### ISSUE TITLE
path setting ignored

### ISSUE THREAD

**Issue by ClayShentrup** [cloudfoundry-incubator/cflocal#36]
E.g.

```
applications:
  - name: notebooks-frontend
    buildpacks:
      - nodejs_buildpack
    command: "yarn serve"
    path: app/notebooks
```

`path` works in `manifest.yml`, but not in `local.yml`. I do see that there's the `-p` option.
